// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module srcnn_top_conv3_Pipeline_VITIS_LOOP_108_1_VITIS_LOOP_109_2_VITIS_LOOP_110_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_w3_AWVALID,
        m_axi_w3_AWREADY,
        m_axi_w3_AWADDR,
        m_axi_w3_AWID,
        m_axi_w3_AWLEN,
        m_axi_w3_AWSIZE,
        m_axi_w3_AWBURST,
        m_axi_w3_AWLOCK,
        m_axi_w3_AWCACHE,
        m_axi_w3_AWPROT,
        m_axi_w3_AWQOS,
        m_axi_w3_AWREGION,
        m_axi_w3_AWUSER,
        m_axi_w3_WVALID,
        m_axi_w3_WREADY,
        m_axi_w3_WDATA,
        m_axi_w3_WSTRB,
        m_axi_w3_WLAST,
        m_axi_w3_WID,
        m_axi_w3_WUSER,
        m_axi_w3_ARVALID,
        m_axi_w3_ARREADY,
        m_axi_w3_ARADDR,
        m_axi_w3_ARID,
        m_axi_w3_ARLEN,
        m_axi_w3_ARSIZE,
        m_axi_w3_ARBURST,
        m_axi_w3_ARLOCK,
        m_axi_w3_ARCACHE,
        m_axi_w3_ARPROT,
        m_axi_w3_ARQOS,
        m_axi_w3_ARREGION,
        m_axi_w3_ARUSER,
        m_axi_w3_RVALID,
        m_axi_w3_RREADY,
        m_axi_w3_RDATA,
        m_axi_w3_RLAST,
        m_axi_w3_RID,
        m_axi_w3_RFIFONUM,
        m_axi_w3_RUSER,
        m_axi_w3_RRESP,
        m_axi_w3_BVALID,
        m_axi_w3_BREADY,
        m_axi_w3_BRESP,
        m_axi_w3_BID,
        m_axi_w3_BUSER,
        m_axi_out_r_AWVALID,
        m_axi_out_r_AWREADY,
        m_axi_out_r_AWADDR,
        m_axi_out_r_AWID,
        m_axi_out_r_AWLEN,
        m_axi_out_r_AWSIZE,
        m_axi_out_r_AWBURST,
        m_axi_out_r_AWLOCK,
        m_axi_out_r_AWCACHE,
        m_axi_out_r_AWPROT,
        m_axi_out_r_AWQOS,
        m_axi_out_r_AWREGION,
        m_axi_out_r_AWUSER,
        m_axi_out_r_WVALID,
        m_axi_out_r_WREADY,
        m_axi_out_r_WDATA,
        m_axi_out_r_WSTRB,
        m_axi_out_r_WLAST,
        m_axi_out_r_WID,
        m_axi_out_r_WUSER,
        m_axi_out_r_ARVALID,
        m_axi_out_r_ARREADY,
        m_axi_out_r_ARADDR,
        m_axi_out_r_ARID,
        m_axi_out_r_ARLEN,
        m_axi_out_r_ARSIZE,
        m_axi_out_r_ARBURST,
        m_axi_out_r_ARLOCK,
        m_axi_out_r_ARCACHE,
        m_axi_out_r_ARPROT,
        m_axi_out_r_ARQOS,
        m_axi_out_r_ARREGION,
        m_axi_out_r_ARUSER,
        m_axi_out_r_RVALID,
        m_axi_out_r_RREADY,
        m_axi_out_r_RDATA,
        m_axi_out_r_RLAST,
        m_axi_out_r_RID,
        m_axi_out_r_RFIFONUM,
        m_axi_out_r_RUSER,
        m_axi_out_r_RRESP,
        m_axi_out_r_BVALID,
        m_axi_out_r_BREADY,
        m_axi_out_r_BRESP,
        m_axi_out_r_BID,
        m_axi_out_r_BUSER,
        select_ln103_1,
        zext_ln103_3,
        b,
        select_ln103_3,
        zext_ln105,
        select_ln103,
        out_ftmap,
        out_tile_address0,
        out_tile_ce0,
        out_tile_q0,
        grp_fu_1054_p_din0,
        grp_fu_1054_p_din1,
        grp_fu_1054_p_opcode,
        grp_fu_1054_p_dout0,
        grp_fu_1054_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_w3_AWVALID;
input   m_axi_w3_AWREADY;
output  [63:0] m_axi_w3_AWADDR;
output  [0:0] m_axi_w3_AWID;
output  [31:0] m_axi_w3_AWLEN;
output  [2:0] m_axi_w3_AWSIZE;
output  [1:0] m_axi_w3_AWBURST;
output  [1:0] m_axi_w3_AWLOCK;
output  [3:0] m_axi_w3_AWCACHE;
output  [2:0] m_axi_w3_AWPROT;
output  [3:0] m_axi_w3_AWQOS;
output  [3:0] m_axi_w3_AWREGION;
output  [0:0] m_axi_w3_AWUSER;
output   m_axi_w3_WVALID;
input   m_axi_w3_WREADY;
output  [31:0] m_axi_w3_WDATA;
output  [3:0] m_axi_w3_WSTRB;
output   m_axi_w3_WLAST;
output  [0:0] m_axi_w3_WID;
output  [0:0] m_axi_w3_WUSER;
output   m_axi_w3_ARVALID;
input   m_axi_w3_ARREADY;
output  [63:0] m_axi_w3_ARADDR;
output  [0:0] m_axi_w3_ARID;
output  [31:0] m_axi_w3_ARLEN;
output  [2:0] m_axi_w3_ARSIZE;
output  [1:0] m_axi_w3_ARBURST;
output  [1:0] m_axi_w3_ARLOCK;
output  [3:0] m_axi_w3_ARCACHE;
output  [2:0] m_axi_w3_ARPROT;
output  [3:0] m_axi_w3_ARQOS;
output  [3:0] m_axi_w3_ARREGION;
output  [0:0] m_axi_w3_ARUSER;
input   m_axi_w3_RVALID;
output   m_axi_w3_RREADY;
input  [31:0] m_axi_w3_RDATA;
input   m_axi_w3_RLAST;
input  [0:0] m_axi_w3_RID;
input  [8:0] m_axi_w3_RFIFONUM;
input  [0:0] m_axi_w3_RUSER;
input  [1:0] m_axi_w3_RRESP;
input   m_axi_w3_BVALID;
output   m_axi_w3_BREADY;
input  [1:0] m_axi_w3_BRESP;
input  [0:0] m_axi_w3_BID;
input  [0:0] m_axi_w3_BUSER;
output   m_axi_out_r_AWVALID;
input   m_axi_out_r_AWREADY;
output  [63:0] m_axi_out_r_AWADDR;
output  [0:0] m_axi_out_r_AWID;
output  [31:0] m_axi_out_r_AWLEN;
output  [2:0] m_axi_out_r_AWSIZE;
output  [1:0] m_axi_out_r_AWBURST;
output  [1:0] m_axi_out_r_AWLOCK;
output  [3:0] m_axi_out_r_AWCACHE;
output  [2:0] m_axi_out_r_AWPROT;
output  [3:0] m_axi_out_r_AWQOS;
output  [3:0] m_axi_out_r_AWREGION;
output  [0:0] m_axi_out_r_AWUSER;
output   m_axi_out_r_WVALID;
input   m_axi_out_r_WREADY;
output  [31:0] m_axi_out_r_WDATA;
output  [3:0] m_axi_out_r_WSTRB;
output   m_axi_out_r_WLAST;
output  [0:0] m_axi_out_r_WID;
output  [0:0] m_axi_out_r_WUSER;
output   m_axi_out_r_ARVALID;
input   m_axi_out_r_ARREADY;
output  [63:0] m_axi_out_r_ARADDR;
output  [0:0] m_axi_out_r_ARID;
output  [31:0] m_axi_out_r_ARLEN;
output  [2:0] m_axi_out_r_ARSIZE;
output  [1:0] m_axi_out_r_ARBURST;
output  [1:0] m_axi_out_r_ARLOCK;
output  [3:0] m_axi_out_r_ARCACHE;
output  [2:0] m_axi_out_r_ARPROT;
output  [3:0] m_axi_out_r_ARQOS;
output  [3:0] m_axi_out_r_ARREGION;
output  [0:0] m_axi_out_r_ARUSER;
input   m_axi_out_r_RVALID;
output   m_axi_out_r_RREADY;
input  [31:0] m_axi_out_r_RDATA;
input   m_axi_out_r_RLAST;
input  [0:0] m_axi_out_r_RID;
input  [8:0] m_axi_out_r_RFIFONUM;
input  [0:0] m_axi_out_r_RUSER;
input  [1:0] m_axi_out_r_RRESP;
input   m_axi_out_r_BVALID;
output   m_axi_out_r_BREADY;
input  [1:0] m_axi_out_r_BRESP;
input  [0:0] m_axi_out_r_BID;
input  [0:0] m_axi_out_r_BUSER;
input  [7:0] select_ln103_1;
input  [7:0] zext_ln103_3;
input  [63:0] b;
input  [7:0] select_ln103_3;
input  [7:0] zext_ln105;
input  [7:0] select_ln103;
input  [63:0] out_ftmap;
output  [12:0] out_tile_address0;
output   out_tile_ce0;
input  [31:0] out_tile_q0;
output  [31:0] grp_fu_1054_p_din0;
output  [31:0] grp_fu_1054_p_din1;
output  [1:0] grp_fu_1054_p_opcode;
input  [31:0] grp_fu_1054_p_dout0;
output   grp_fu_1054_p_ce;

reg ap_idle;
reg m_axi_w3_ARVALID;
reg m_axi_w3_RREADY;
reg m_axi_out_r_AWVALID;
reg m_axi_out_r_WVALID;
reg m_axi_out_r_BREADY;
reg out_tile_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg   [0:0] and_ln112_reg_819;
reg    ap_block_state3_io;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
reg   [0:0] and_ln112_reg_819_pp0_iter9_reg;
reg    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
reg   [0:0] and_ln112_reg_819_pp0_iter13_reg;
reg    ap_block_state15_io;
wire    ap_block_state16_pp0_stage0_iter15;
reg   [0:0] and_ln112_reg_819_pp0_iter14_reg;
reg    ap_block_state16_io;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
wire    ap_block_state20_pp0_stage0_iter19;
reg   [0:0] and_ln112_reg_819_pp0_iter19_reg;
reg    ap_block_state21_pp0_stage0_iter20;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln108_fu_289_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    w3_blk_n_AR;
wire    ap_block_pp0_stage0;
reg    w3_blk_n_R;
reg    out_r_blk_n_AW;
reg    out_r_blk_n_W;
reg    out_r_blk_n_B;
reg    ap_block_pp0_stage0_11001;
wire   [3:0] select_ln108_1_fu_327_p3;
reg   [3:0] select_ln108_1_reg_797;
reg   [3:0] select_ln108_1_reg_797_pp0_iter2_reg;
reg   [3:0] select_ln108_1_reg_797_pp0_iter3_reg;
reg   [3:0] select_ln108_1_reg_797_pp0_iter4_reg;
reg   [3:0] select_ln108_1_reg_797_pp0_iter5_reg;
reg   [3:0] select_ln108_1_reg_797_pp0_iter6_reg;
reg   [3:0] select_ln108_1_reg_797_pp0_iter7_reg;
reg   [3:0] select_ln108_1_reg_797_pp0_iter8_reg;
reg   [3:0] select_ln108_1_reg_797_pp0_iter9_reg;
reg   [3:0] select_ln108_1_reg_797_pp0_iter10_reg;
reg   [3:0] select_ln108_1_reg_797_pp0_iter11_reg;
reg   [3:0] select_ln108_1_reg_797_pp0_iter12_reg;
wire   [5:0] select_ln109_fu_438_p3;
reg   [5:0] select_ln109_reg_802;
reg   [5:0] select_ln109_reg_802_pp0_iter2_reg;
reg   [5:0] select_ln109_reg_802_pp0_iter3_reg;
reg   [5:0] select_ln109_reg_802_pp0_iter4_reg;
reg   [5:0] select_ln109_reg_802_pp0_iter5_reg;
reg   [5:0] select_ln109_reg_802_pp0_iter6_reg;
reg   [5:0] select_ln109_reg_802_pp0_iter7_reg;
reg   [5:0] select_ln109_reg_802_pp0_iter8_reg;
wire   [7:0] add_ln113_3_fu_458_p2;
reg   [7:0] add_ln113_3_reg_808;
reg   [7:0] add_ln113_3_reg_808_pp0_iter2_reg;
reg   [7:0] add_ln113_3_reg_808_pp0_iter3_reg;
reg   [7:0] add_ln113_3_reg_808_pp0_iter4_reg;
reg   [7:0] add_ln113_3_reg_808_pp0_iter5_reg;
reg   [7:0] add_ln113_3_reg_808_pp0_iter6_reg;
reg   [7:0] add_ln113_3_reg_808_pp0_iter7_reg;
reg   [7:0] add_ln113_3_reg_808_pp0_iter8_reg;
wire   [7:0] select_ln109_2_fu_473_p3;
reg   [7:0] select_ln109_2_reg_813;
reg   [7:0] select_ln109_2_reg_813_pp0_iter2_reg;
reg   [7:0] select_ln109_2_reg_813_pp0_iter3_reg;
reg   [7:0] select_ln109_2_reg_813_pp0_iter4_reg;
reg   [7:0] select_ln109_2_reg_813_pp0_iter5_reg;
reg   [7:0] select_ln109_2_reg_813_pp0_iter6_reg;
reg   [7:0] select_ln109_2_reg_813_pp0_iter7_reg;
reg   [7:0] select_ln109_2_reg_813_pp0_iter8_reg;
reg   [7:0] select_ln109_2_reg_813_pp0_iter9_reg;
reg   [7:0] select_ln109_2_reg_813_pp0_iter10_reg;
reg   [7:0] select_ln109_2_reg_813_pp0_iter11_reg;
reg   [7:0] select_ln109_2_reg_813_pp0_iter12_reg;
wire   [0:0] and_ln112_fu_509_p2;
reg   [0:0] and_ln112_reg_819_pp0_iter2_reg;
reg   [0:0] and_ln112_reg_819_pp0_iter3_reg;
reg   [0:0] and_ln112_reg_819_pp0_iter4_reg;
reg   [0:0] and_ln112_reg_819_pp0_iter5_reg;
reg   [0:0] and_ln112_reg_819_pp0_iter6_reg;
reg   [0:0] and_ln112_reg_819_pp0_iter7_reg;
reg   [0:0] and_ln112_reg_819_pp0_iter8_reg;
reg   [0:0] and_ln112_reg_819_pp0_iter10_reg;
reg   [0:0] and_ln112_reg_819_pp0_iter11_reg;
reg   [0:0] and_ln112_reg_819_pp0_iter12_reg;
reg   [0:0] and_ln112_reg_819_pp0_iter15_reg;
reg   [0:0] and_ln112_reg_819_pp0_iter16_reg;
reg   [0:0] and_ln112_reg_819_pp0_iter17_reg;
reg   [0:0] and_ln112_reg_819_pp0_iter18_reg;
reg   [63:0] w3_addr_reg_823;
wire   [4:0] trunc_ln113_1_fu_601_p1;
reg   [4:0] trunc_ln113_1_reg_834;
reg   [4:0] trunc_ln113_1_reg_834_pp0_iter10_reg;
reg   [4:0] trunc_ln113_1_reg_834_pp0_iter11_reg;
reg   [4:0] trunc_ln113_1_reg_834_pp0_iter12_reg;
reg   [31:0] out_tile_load_reg_839;
reg   [31:0] w3_addr_read_reg_844;
wire   [31:0] bitcast_ln113_fu_604_p1;
reg   [63:0] out_r_addr_reg_854;
reg   [31:0] add19_i_reg_860;
wire   [63:0] zext_ln113_6_fu_596_p1;
wire  signed [63:0] sext_ln113_fu_525_p1;
wire  signed [63:0] sext_ln113_1_fu_706_p1;
reg    ap_block_pp0_stage0_01001;
reg   [5:0] tw_fu_134;
wire   [5:0] add_ln110_fu_535_p2;
wire    ap_loop_init;
reg   [5:0] th_1_fu_138;
wire   [5:0] select_ln109_1_fu_446_p3;
reg   [11:0] indvar_flatten55_fu_142;
wire   [11:0] select_ln109_4_fu_547_p3;
reg   [3:0] tn_fu_146;
reg   [13:0] indvar_flatten86_fu_150;
wire   [13:0] add_ln108_2_fu_295_p2;
wire   [7:0] zext_ln109_fu_275_p1;
wire   [0:0] icmp_ln109_fu_313_p2;
wire   [3:0] add_ln108_fu_307_p2;
wire   [2:0] trunc_ln113_fu_335_p1;
wire   [2:0] trunc_ln108_fu_347_p1;
wire   [4:0] p_mid269_v_v_fu_351_p3;
wire   [63:0] zext_ln108_1_fu_359_p1;
wire   [0:0] notlhs_mid1_fu_368_p2;
wire   [0:0] notlhs438_fu_374_p2;
wire   [7:0] empty_fu_279_p2;
wire   [0:0] notrhs_mid182_fu_395_p2;
wire   [0:0] notrhs_fu_284_p2;
wire   [0:0] icmp_ln110_fu_414_p2;
wire   [0:0] xor_ln108_fu_408_p2;
wire   [5:0] select_ln108_fu_319_p3;
wire   [0:0] and_ln108_fu_420_p2;
wire   [0:0] or_ln109_fu_432_p2;
wire   [5:0] add_ln109_fu_426_p2;
wire   [7:0] tmp_5_cast_fu_339_p3;
wire   [7:0] zext_ln113_3_fu_454_p1;
wire   [7:0] zext_ln109_1_fu_464_p1;
wire   [7:0] p_mid153_fu_468_p2;
wire   [7:0] select_ln108_3_fu_388_p3;
wire   [0:0] notrhs_mid1_fu_481_p2;
wire   [0:0] select_ln108_4_fu_400_p3;
wire   [7:0] zext_ln111_fu_494_p1;
wire   [0:0] icmp_ln112_fu_498_p2;
wire   [0:0] select_ln108_2_fu_380_p3;
wire   [0:0] and_ln112_1_fu_503_p2;
wire   [0:0] select_ln109_3_fu_486_p3;
wire   [63:0] add_ln108_1_fu_363_p2;
wire   [61:0] trunc_ln5_fu_515_p4;
wire   [11:0] add_ln109_1_fu_541_p2;
wire   [12:0] tmp_8_fu_580_p3;
wire   [12:0] zext_ln113_5_fu_587_p1;
wire   [12:0] add_ln113_4_fu_590_p2;
wire   [3:0] mul_ln113_fu_611_p0;
wire   [18:0] mul_ln113_fu_611_p1;
wire   [21:0] mul_ln113_fu_611_p2;
wire   [17:0] shl_ln1_fu_621_p3;
wire   [9:0] shl_ln113_1_fu_632_p3;
wire   [18:0] zext_ln113_1_fu_628_p1;
wire   [18:0] zext_ln113_2_fu_639_p1;
wire   [18:0] sub_ln113_fu_643_p2;
wire   [2:0] tmp_fu_653_p4;
wire   [9:0] tmp_s_fu_662_p4;
wire   [63:0] zext_ln113_fu_617_p1;
wire  signed [19:0] sext_ln113_2_fu_649_p1;
wire   [19:0] zext_ln113_4_fu_671_p1;
wire   [19:0] add_ln113_1_fu_680_p2;
wire  signed [63:0] sext_ln113_3_fu_686_p1;
wire   [63:0] add_ln113_fu_675_p2;
wire   [63:0] add_ln113_2_fu_690_p2;
wire   [61:0] trunc_ln113_2_fu_696_p4;
reg    grp_fu_237_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_block_pp0_stage0_00001;
wire   [21:0] mul_ln113_fu_611_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_done_reg = 1'b0;
end

srcnn_top_mul_4ns_19ns_22_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 19 ),
    .dout_WIDTH( 22 ))
mul_4ns_19ns_22_1_1_U1730(
    .din0(mul_ln113_fu_611_p0),
    .din1(mul_ln113_fu_611_p1),
    .dout(mul_ln113_fu_611_p2)
);

srcnn_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter19_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten55_fu_142 <= 12'd0;
        end else if (((icmp_ln108_fu_289_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten55_fu_142 <= select_ln109_4_fu_547_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten86_fu_150 <= 14'd0;
        end else if (((icmp_ln108_fu_289_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten86_fu_150 <= add_ln108_2_fu_295_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            th_1_fu_138 <= 6'd0;
        end else if (((icmp_ln108_fu_289_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            th_1_fu_138 <= select_ln109_1_fu_446_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            tn_fu_146 <= 4'd0;
        end else if (((icmp_ln108_fu_289_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            tn_fu_146 <= select_ln108_1_fu_327_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            tw_fu_134 <= 6'd0;
        end else if (((icmp_ln108_fu_289_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            tw_fu_134 <= add_ln110_fu_535_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln112_reg_819_pp0_iter13_reg))) begin
        add19_i_reg_860 <= grp_fu_1054_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln108_fu_289_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln113_3_reg_808 <= add_ln113_3_fu_458_p2;
        and_ln112_reg_819 <= and_ln112_fu_509_p2;
        select_ln108_1_reg_797 <= select_ln108_1_fu_327_p3;
        select_ln109_2_reg_813 <= select_ln109_2_fu_473_p3;
        select_ln109_reg_802 <= select_ln109_fu_438_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln113_3_reg_808_pp0_iter2_reg <= add_ln113_3_reg_808;
        add_ln113_3_reg_808_pp0_iter3_reg <= add_ln113_3_reg_808_pp0_iter2_reg;
        add_ln113_3_reg_808_pp0_iter4_reg <= add_ln113_3_reg_808_pp0_iter3_reg;
        add_ln113_3_reg_808_pp0_iter5_reg <= add_ln113_3_reg_808_pp0_iter4_reg;
        add_ln113_3_reg_808_pp0_iter6_reg <= add_ln113_3_reg_808_pp0_iter5_reg;
        add_ln113_3_reg_808_pp0_iter7_reg <= add_ln113_3_reg_808_pp0_iter6_reg;
        add_ln113_3_reg_808_pp0_iter8_reg <= add_ln113_3_reg_808_pp0_iter7_reg;
        and_ln112_reg_819_pp0_iter10_reg <= and_ln112_reg_819_pp0_iter9_reg;
        and_ln112_reg_819_pp0_iter11_reg <= and_ln112_reg_819_pp0_iter10_reg;
        and_ln112_reg_819_pp0_iter12_reg <= and_ln112_reg_819_pp0_iter11_reg;
        and_ln112_reg_819_pp0_iter13_reg <= and_ln112_reg_819_pp0_iter12_reg;
        and_ln112_reg_819_pp0_iter14_reg <= and_ln112_reg_819_pp0_iter13_reg;
        and_ln112_reg_819_pp0_iter15_reg <= and_ln112_reg_819_pp0_iter14_reg;
        and_ln112_reg_819_pp0_iter16_reg <= and_ln112_reg_819_pp0_iter15_reg;
        and_ln112_reg_819_pp0_iter17_reg <= and_ln112_reg_819_pp0_iter16_reg;
        and_ln112_reg_819_pp0_iter18_reg <= and_ln112_reg_819_pp0_iter17_reg;
        and_ln112_reg_819_pp0_iter19_reg <= and_ln112_reg_819_pp0_iter18_reg;
        and_ln112_reg_819_pp0_iter2_reg <= and_ln112_reg_819;
        and_ln112_reg_819_pp0_iter3_reg <= and_ln112_reg_819_pp0_iter2_reg;
        and_ln112_reg_819_pp0_iter4_reg <= and_ln112_reg_819_pp0_iter3_reg;
        and_ln112_reg_819_pp0_iter5_reg <= and_ln112_reg_819_pp0_iter4_reg;
        and_ln112_reg_819_pp0_iter6_reg <= and_ln112_reg_819_pp0_iter5_reg;
        and_ln112_reg_819_pp0_iter7_reg <= and_ln112_reg_819_pp0_iter6_reg;
        and_ln112_reg_819_pp0_iter8_reg <= and_ln112_reg_819_pp0_iter7_reg;
        and_ln112_reg_819_pp0_iter9_reg <= and_ln112_reg_819_pp0_iter8_reg;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        select_ln108_1_reg_797_pp0_iter10_reg <= select_ln108_1_reg_797_pp0_iter9_reg;
        select_ln108_1_reg_797_pp0_iter11_reg <= select_ln108_1_reg_797_pp0_iter10_reg;
        select_ln108_1_reg_797_pp0_iter12_reg <= select_ln108_1_reg_797_pp0_iter11_reg;
        select_ln108_1_reg_797_pp0_iter2_reg <= select_ln108_1_reg_797;
        select_ln108_1_reg_797_pp0_iter3_reg <= select_ln108_1_reg_797_pp0_iter2_reg;
        select_ln108_1_reg_797_pp0_iter4_reg <= select_ln108_1_reg_797_pp0_iter3_reg;
        select_ln108_1_reg_797_pp0_iter5_reg <= select_ln108_1_reg_797_pp0_iter4_reg;
        select_ln108_1_reg_797_pp0_iter6_reg <= select_ln108_1_reg_797_pp0_iter5_reg;
        select_ln108_1_reg_797_pp0_iter7_reg <= select_ln108_1_reg_797_pp0_iter6_reg;
        select_ln108_1_reg_797_pp0_iter8_reg <= select_ln108_1_reg_797_pp0_iter7_reg;
        select_ln108_1_reg_797_pp0_iter9_reg <= select_ln108_1_reg_797_pp0_iter8_reg;
        select_ln109_2_reg_813_pp0_iter10_reg <= select_ln109_2_reg_813_pp0_iter9_reg;
        select_ln109_2_reg_813_pp0_iter11_reg <= select_ln109_2_reg_813_pp0_iter10_reg;
        select_ln109_2_reg_813_pp0_iter12_reg <= select_ln109_2_reg_813_pp0_iter11_reg;
        select_ln109_2_reg_813_pp0_iter2_reg <= select_ln109_2_reg_813;
        select_ln109_2_reg_813_pp0_iter3_reg <= select_ln109_2_reg_813_pp0_iter2_reg;
        select_ln109_2_reg_813_pp0_iter4_reg <= select_ln109_2_reg_813_pp0_iter3_reg;
        select_ln109_2_reg_813_pp0_iter5_reg <= select_ln109_2_reg_813_pp0_iter4_reg;
        select_ln109_2_reg_813_pp0_iter6_reg <= select_ln109_2_reg_813_pp0_iter5_reg;
        select_ln109_2_reg_813_pp0_iter7_reg <= select_ln109_2_reg_813_pp0_iter6_reg;
        select_ln109_2_reg_813_pp0_iter8_reg <= select_ln109_2_reg_813_pp0_iter7_reg;
        select_ln109_2_reg_813_pp0_iter9_reg <= select_ln109_2_reg_813_pp0_iter8_reg;
        select_ln109_reg_802_pp0_iter2_reg <= select_ln109_reg_802;
        select_ln109_reg_802_pp0_iter3_reg <= select_ln109_reg_802_pp0_iter2_reg;
        select_ln109_reg_802_pp0_iter4_reg <= select_ln109_reg_802_pp0_iter3_reg;
        select_ln109_reg_802_pp0_iter5_reg <= select_ln109_reg_802_pp0_iter4_reg;
        select_ln109_reg_802_pp0_iter6_reg <= select_ln109_reg_802_pp0_iter5_reg;
        select_ln109_reg_802_pp0_iter7_reg <= select_ln109_reg_802_pp0_iter6_reg;
        select_ln109_reg_802_pp0_iter8_reg <= select_ln109_reg_802_pp0_iter7_reg;
        trunc_ln113_1_reg_834_pp0_iter10_reg <= trunc_ln113_1_reg_834;
        trunc_ln113_1_reg_834_pp0_iter11_reg <= trunc_ln113_1_reg_834_pp0_iter10_reg;
        trunc_ln113_1_reg_834_pp0_iter12_reg <= trunc_ln113_1_reg_834_pp0_iter11_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln112_reg_819_pp0_iter12_reg))) begin
        out_r_addr_reg_854 <= sext_ln113_1_fu_706_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln112_reg_819_pp0_iter9_reg))) begin
        out_tile_load_reg_839 <= out_tile_q0;
        w3_addr_read_reg_844 <= m_axi_w3_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln112_reg_819_pp0_iter8_reg))) begin
        trunc_ln113_1_reg_834 <= trunc_ln113_1_fu_601_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln108_fu_289_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'd1 == and_ln112_fu_509_p2))) begin
        w3_addr_reg_823 <= sext_ln113_fu_525_p1;
    end
end

always @ (*) begin
    if (((icmp_ln108_fu_289_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter19_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_237_ce = 1'b1;
    end else begin
        grp_fu_237_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln112_reg_819_pp0_iter13_reg))) begin
        m_axi_out_r_AWVALID = 1'b1;
    end else begin
        m_axi_out_r_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln112_reg_819_pp0_iter19_reg))) begin
        m_axi_out_r_BREADY = 1'b1;
    end else begin
        m_axi_out_r_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln112_reg_819_pp0_iter14_reg))) begin
        m_axi_out_r_WVALID = 1'b1;
    end else begin
        m_axi_out_r_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln112_reg_819))) begin
        m_axi_w3_ARVALID = 1'b1;
    end else begin
        m_axi_w3_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln112_reg_819_pp0_iter9_reg))) begin
        m_axi_w3_RREADY = 1'b1;
    end else begin
        m_axi_w3_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'd1 == and_ln112_reg_819_pp0_iter13_reg))) begin
        out_r_blk_n_AW = m_axi_out_r_AWREADY;
    end else begin
        out_r_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'd1 == and_ln112_reg_819_pp0_iter19_reg))) begin
        out_r_blk_n_B = m_axi_out_r_BVALID;
    end else begin
        out_r_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'd1 == and_ln112_reg_819_pp0_iter14_reg))) begin
        out_r_blk_n_W = m_axi_out_r_WREADY;
    end else begin
        out_r_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        out_tile_ce0 = 1'b1;
    end else begin
        out_tile_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'd1 == and_ln112_reg_819))) begin
        w3_blk_n_AR = m_axi_w3_ARREADY;
    end else begin
        w3_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'd1 == and_ln112_reg_819_pp0_iter9_reg))) begin
        w3_blk_n_R = m_axi_w3_RVALID;
    end else begin
        w3_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln108_1_fu_363_p2 = (zext_ln108_1_fu_359_p1 + b);

assign add_ln108_2_fu_295_p2 = (indvar_flatten86_fu_150 + 14'd1);

assign add_ln108_fu_307_p2 = (tn_fu_146 + 4'd1);

assign add_ln109_1_fu_541_p2 = (indvar_flatten55_fu_142 + 12'd1);

assign add_ln109_fu_426_p2 = (select_ln108_fu_319_p3 + 6'd1);

assign add_ln110_fu_535_p2 = (select_ln109_fu_438_p3 + 6'd1);

assign add_ln113_1_fu_680_p2 = ($signed(sext_ln113_2_fu_649_p1) + $signed(zext_ln113_4_fu_671_p1));

assign add_ln113_2_fu_690_p2 = ($signed(sext_ln113_3_fu_686_p1) + $signed(add_ln113_fu_675_p2));

assign add_ln113_3_fu_458_p2 = (tmp_5_cast_fu_339_p3 + zext_ln113_3_fu_454_p1);

assign add_ln113_4_fu_590_p2 = (tmp_8_fu_580_p3 + zext_ln113_5_fu_587_p1);

assign add_ln113_fu_675_p2 = (zext_ln113_fu_617_p1 + out_ftmap);

assign and_ln108_fu_420_p2 = (xor_ln108_fu_408_p2 & icmp_ln110_fu_414_p2);

assign and_ln112_1_fu_503_p2 = (select_ln108_2_fu_380_p3 & icmp_ln112_fu_498_p2);

assign and_ln112_fu_509_p2 = (select_ln109_3_fu_486_p3 & and_ln112_1_fu_503_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_00001 = (((ap_enable_reg_pp0_iter20 == 1'b1) & (m_axi_out_r_BVALID == 1'b0) & (1'd1 == and_ln112_reg_819_pp0_iter19_reg)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'd1 == and_ln112_reg_819_pp0_iter9_reg) & (m_axi_w3_RVALID == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter20 == 1'b1) & (m_axi_out_r_BVALID == 1'b0) & (1'd1 == and_ln112_reg_819_pp0_iter19_reg)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'd1 == and_ln112_reg_819_pp0_iter9_reg) & (m_axi_w3_RVALID == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter20 == 1'b1) & (m_axi_out_r_BVALID == 1'b0) & (1'd1 == and_ln112_reg_819_pp0_iter19_reg)) | ((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b1 == ap_block_state16_io)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b1 == ap_block_state15_io)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'd1 == and_ln112_reg_819_pp0_iter9_reg) & (m_axi_w3_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter20 == 1'b1) & (m_axi_out_r_BVALID == 1'b0) & (1'd1 == and_ln112_reg_819_pp0_iter19_reg)) | ((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b1 == ap_block_state16_io)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b1 == ap_block_state15_io)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'd1 == and_ln112_reg_819_pp0_iter9_reg) & (m_axi_w3_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_io)));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state11_pp0_stage0_iter10 = ((1'd1 == and_ln112_reg_819_pp0_iter9_reg) & (m_axi_w3_RVALID == 1'b0));
end

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state15_io = ((m_axi_out_r_AWREADY == 1'b0) & (1'd1 == and_ln112_reg_819_pp0_iter13_reg));
end

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state16_io = ((m_axi_out_r_WREADY == 1'b0) & (1'd1 == and_ln112_reg_819_pp0_iter14_reg));
end

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state21_pp0_stage0_iter20 = ((m_axi_out_r_BVALID == 1'b0) & (1'd1 == and_ln112_reg_819_pp0_iter19_reg));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_io = ((1'd1 == and_ln112_reg_819) & (m_axi_w3_ARREADY == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign bitcast_ln113_fu_604_p1 = w3_addr_read_reg_844;

assign empty_fu_279_p2 = (zext_ln109_fu_275_p1 + select_ln103_1);

assign grp_fu_1054_p_ce = grp_fu_237_ce;

assign grp_fu_1054_p_din0 = out_tile_load_reg_839;

assign grp_fu_1054_p_din1 = bitcast_ln113_fu_604_p1;

assign grp_fu_1054_p_opcode = 2'd0;

assign icmp_ln108_fu_289_p2 = ((indvar_flatten86_fu_150 == 14'd8192) ? 1'b1 : 1'b0);

assign icmp_ln109_fu_313_p2 = ((indvar_flatten55_fu_142 == 12'd1024) ? 1'b1 : 1'b0);

assign icmp_ln110_fu_414_p2 = ((tw_fu_134 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln112_fu_498_p2 = ((zext_ln111_fu_494_p1 < zext_ln105) ? 1'b1 : 1'b0);

assign m_axi_out_r_ARADDR = 64'd0;

assign m_axi_out_r_ARBURST = 2'd0;

assign m_axi_out_r_ARCACHE = 4'd0;

assign m_axi_out_r_ARID = 1'd0;

assign m_axi_out_r_ARLEN = 32'd0;

assign m_axi_out_r_ARLOCK = 2'd0;

assign m_axi_out_r_ARPROT = 3'd0;

assign m_axi_out_r_ARQOS = 4'd0;

assign m_axi_out_r_ARREGION = 4'd0;

assign m_axi_out_r_ARSIZE = 3'd0;

assign m_axi_out_r_ARUSER = 1'd0;

assign m_axi_out_r_ARVALID = 1'b0;

assign m_axi_out_r_AWADDR = out_r_addr_reg_854;

assign m_axi_out_r_AWBURST = 2'd0;

assign m_axi_out_r_AWCACHE = 4'd0;

assign m_axi_out_r_AWID = 1'd0;

assign m_axi_out_r_AWLEN = 32'd1;

assign m_axi_out_r_AWLOCK = 2'd0;

assign m_axi_out_r_AWPROT = 3'd0;

assign m_axi_out_r_AWQOS = 4'd0;

assign m_axi_out_r_AWREGION = 4'd0;

assign m_axi_out_r_AWSIZE = 3'd0;

assign m_axi_out_r_AWUSER = 1'd0;

assign m_axi_out_r_RREADY = 1'b0;

assign m_axi_out_r_WDATA = add19_i_reg_860;

assign m_axi_out_r_WID = 1'd0;

assign m_axi_out_r_WLAST = 1'b0;

assign m_axi_out_r_WSTRB = 4'd15;

assign m_axi_out_r_WUSER = 1'd0;

assign m_axi_w3_ARADDR = w3_addr_reg_823;

assign m_axi_w3_ARBURST = 2'd0;

assign m_axi_w3_ARCACHE = 4'd0;

assign m_axi_w3_ARID = 1'd0;

assign m_axi_w3_ARLEN = 32'd1;

assign m_axi_w3_ARLOCK = 2'd0;

assign m_axi_w3_ARPROT = 3'd0;

assign m_axi_w3_ARQOS = 4'd0;

assign m_axi_w3_ARREGION = 4'd0;

assign m_axi_w3_ARSIZE = 3'd0;

assign m_axi_w3_ARUSER = 1'd0;

assign m_axi_w3_AWADDR = 64'd0;

assign m_axi_w3_AWBURST = 2'd0;

assign m_axi_w3_AWCACHE = 4'd0;

assign m_axi_w3_AWID = 1'd0;

assign m_axi_w3_AWLEN = 32'd0;

assign m_axi_w3_AWLOCK = 2'd0;

assign m_axi_w3_AWPROT = 3'd0;

assign m_axi_w3_AWQOS = 4'd0;

assign m_axi_w3_AWREGION = 4'd0;

assign m_axi_w3_AWSIZE = 3'd0;

assign m_axi_w3_AWUSER = 1'd0;

assign m_axi_w3_AWVALID = 1'b0;

assign m_axi_w3_BREADY = 1'b0;

assign m_axi_w3_WDATA = 32'd0;

assign m_axi_w3_WID = 1'd0;

assign m_axi_w3_WLAST = 1'b0;

assign m_axi_w3_WSTRB = 4'd0;

assign m_axi_w3_WUSER = 1'd0;

assign m_axi_w3_WVALID = 1'b0;

assign mul_ln113_fu_611_p0 = mul_ln113_fu_611_p00;

assign mul_ln113_fu_611_p00 = select_ln108_1_reg_797_pp0_iter12_reg;

assign mul_ln113_fu_611_p1 = 22'd260100;

assign notlhs438_fu_374_p2 = ((tn_fu_146 == 4'd0) ? 1'b1 : 1'b0);

assign notlhs_mid1_fu_368_p2 = ((add_ln108_fu_307_p2 == 4'd0) ? 1'b1 : 1'b0);

assign notrhs_fu_284_p2 = ((zext_ln109_fu_275_p1 < zext_ln103_3) ? 1'b1 : 1'b0);

assign notrhs_mid182_fu_395_p2 = ((select_ln103_3 != 8'd0) ? 1'b1 : 1'b0);

assign notrhs_mid1_fu_481_p2 = ((zext_ln109_1_fu_464_p1 < zext_ln103_3) ? 1'b1 : 1'b0);

assign or_ln109_fu_432_p2 = (icmp_ln109_fu_313_p2 | and_ln108_fu_420_p2);

assign out_tile_address0 = zext_ln113_6_fu_596_p1;

assign p_mid153_fu_468_p2 = (zext_ln109_1_fu_464_p1 + select_ln103_1);

assign p_mid269_v_v_fu_351_p3 = {{trunc_ln108_fu_347_p1}, {2'd0}};

assign select_ln108_1_fu_327_p3 = ((icmp_ln109_fu_313_p2[0:0] == 1'b1) ? add_ln108_fu_307_p2 : tn_fu_146);

assign select_ln108_2_fu_380_p3 = ((icmp_ln109_fu_313_p2[0:0] == 1'b1) ? notlhs_mid1_fu_368_p2 : notlhs438_fu_374_p2);

assign select_ln108_3_fu_388_p3 = ((icmp_ln109_fu_313_p2[0:0] == 1'b1) ? select_ln103_1 : empty_fu_279_p2);

assign select_ln108_4_fu_400_p3 = ((icmp_ln109_fu_313_p2[0:0] == 1'b1) ? notrhs_mid182_fu_395_p2 : notrhs_fu_284_p2);

assign select_ln108_fu_319_p3 = ((icmp_ln109_fu_313_p2[0:0] == 1'b1) ? 6'd0 : th_1_fu_138);

assign select_ln109_1_fu_446_p3 = ((and_ln108_fu_420_p2[0:0] == 1'b1) ? add_ln109_fu_426_p2 : select_ln108_fu_319_p3);

assign select_ln109_2_fu_473_p3 = ((and_ln108_fu_420_p2[0:0] == 1'b1) ? p_mid153_fu_468_p2 : select_ln108_3_fu_388_p3);

assign select_ln109_3_fu_486_p3 = ((and_ln108_fu_420_p2[0:0] == 1'b1) ? notrhs_mid1_fu_481_p2 : select_ln108_4_fu_400_p3);

assign select_ln109_4_fu_547_p3 = ((icmp_ln109_fu_313_p2[0:0] == 1'b1) ? 12'd1 : add_ln109_1_fu_541_p2);

assign select_ln109_fu_438_p3 = ((or_ln109_fu_432_p2[0:0] == 1'b1) ? 6'd0 : tw_fu_134);

assign sext_ln113_1_fu_706_p1 = $signed(trunc_ln113_2_fu_696_p4);

assign sext_ln113_2_fu_649_p1 = $signed(sub_ln113_fu_643_p2);

assign sext_ln113_3_fu_686_p1 = $signed(add_ln113_1_fu_680_p2);

assign sext_ln113_fu_525_p1 = $signed(trunc_ln5_fu_515_p4);

assign shl_ln113_1_fu_632_p3 = {{select_ln109_2_reg_813_pp0_iter12_reg}, {2'd0}};

assign shl_ln1_fu_621_p3 = {{select_ln109_2_reg_813_pp0_iter12_reg}, {10'd0}};

assign sub_ln113_fu_643_p2 = (zext_ln113_1_fu_628_p1 - zext_ln113_2_fu_639_p1);

assign tmp_5_cast_fu_339_p3 = {{trunc_ln113_fu_335_p1}, {5'd0}};

assign tmp_8_fu_580_p3 = {{add_ln113_3_reg_808_pp0_iter8_reg}, {5'd0}};

assign tmp_fu_653_p4 = {{select_ln103[7:5]}};

assign tmp_s_fu_662_p4 = {{{tmp_fu_653_p4}, {trunc_ln113_1_reg_834_pp0_iter12_reg}}, {2'd0}};

assign trunc_ln108_fu_347_p1 = select_ln108_1_fu_327_p3[2:0];

assign trunc_ln113_1_fu_601_p1 = select_ln109_reg_802_pp0_iter8_reg[4:0];

assign trunc_ln113_2_fu_696_p4 = {{add_ln113_2_fu_690_p2[63:2]}};

assign trunc_ln113_fu_335_p1 = select_ln108_1_fu_327_p3[2:0];

assign trunc_ln5_fu_515_p4 = {{add_ln108_1_fu_363_p2[63:2]}};

assign xor_ln108_fu_408_p2 = (icmp_ln109_fu_313_p2 ^ 1'd1);

assign zext_ln108_1_fu_359_p1 = p_mid269_v_v_fu_351_p3;

assign zext_ln109_1_fu_464_p1 = add_ln109_fu_426_p2;

assign zext_ln109_fu_275_p1 = th_1_fu_138;

assign zext_ln111_fu_494_p1 = select_ln109_fu_438_p3;

assign zext_ln113_1_fu_628_p1 = shl_ln1_fu_621_p3;

assign zext_ln113_2_fu_639_p1 = shl_ln113_1_fu_632_p3;

assign zext_ln113_3_fu_454_p1 = select_ln109_1_fu_446_p3;

assign zext_ln113_4_fu_671_p1 = tmp_s_fu_662_p4;

assign zext_ln113_5_fu_587_p1 = select_ln109_reg_802_pp0_iter8_reg;

assign zext_ln113_6_fu_596_p1 = add_ln113_4_fu_590_p2;

assign zext_ln113_fu_617_p1 = mul_ln113_fu_611_p2;

endmodule //srcnn_top_conv3_Pipeline_VITIS_LOOP_108_1_VITIS_LOOP_109_2_VITIS_LOOP_110_3
