-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity srcnn_conv1 is
port (
    m_axi_gmem_in_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_in_AWREADY : IN STD_LOGIC;
    m_axi_gmem_in_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_in_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_in_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_in_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_in_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_WVALID : OUT STD_LOGIC;
    m_axi_gmem_in_WREADY : IN STD_LOGIC;
    m_axi_gmem_in_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_in_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_WLAST : OUT STD_LOGIC;
    m_axi_gmem_in_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_in_ARREADY : IN STD_LOGIC;
    m_axi_gmem_in_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_in_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_in_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_in_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_in_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_RVALID : IN STD_LOGIC;
    m_axi_gmem_in_RREADY : OUT STD_LOGIC;
    m_axi_gmem_in_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_in_RLAST : IN STD_LOGIC;
    m_axi_gmem_in_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_RFIFONUM : IN STD_LOGIC_VECTOR (12 downto 0);
    m_axi_gmem_in_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_BVALID : IN STD_LOGIC;
    m_axi_gmem_in_BREADY : OUT STD_LOGIC;
    m_axi_gmem_in_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    input_ftmap : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_wgt_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_wgt_AWREADY : IN STD_LOGIC;
    m_axi_gmem_wgt_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_wgt_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_wgt_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_wgt_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_wgt_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_wgt_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_wgt_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_wgt_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_wgt_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_wgt_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_wgt_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_wgt_WVALID : OUT STD_LOGIC;
    m_axi_gmem_wgt_WREADY : IN STD_LOGIC;
    m_axi_gmem_wgt_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_wgt_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_wgt_WLAST : OUT STD_LOGIC;
    m_axi_gmem_wgt_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_wgt_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_wgt_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_wgt_ARREADY : IN STD_LOGIC;
    m_axi_gmem_wgt_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_wgt_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_wgt_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_wgt_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_wgt_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_wgt_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_wgt_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_wgt_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_wgt_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_wgt_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_wgt_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_wgt_RVALID : IN STD_LOGIC;
    m_axi_gmem_wgt_RREADY : OUT STD_LOGIC;
    m_axi_gmem_wgt_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_wgt_RLAST : IN STD_LOGIC;
    m_axi_gmem_wgt_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_wgt_RFIFONUM : IN STD_LOGIC_VECTOR (13 downto 0);
    m_axi_gmem_wgt_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_wgt_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_wgt_BVALID : IN STD_LOGIC;
    m_axi_gmem_wgt_BREADY : OUT STD_LOGIC;
    m_axi_gmem_wgt_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_wgt_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_wgt_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    conv1_weights : IN STD_LOGIC_VECTOR (63 downto 0);
    conv1_biases : IN STD_LOGIC_VECTOR (63 downto 0);
    feat1_address0 : OUT STD_LOGIC_VECTOR (21 downto 0);
    feat1_ce0 : OUT STD_LOGIC;
    feat1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    feat1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    feat1_we0 : OUT STD_LOGIC;
    feat1_address1 : OUT STD_LOGIC_VECTOR (21 downto 0);
    feat1_ce1 : OUT STD_LOGIC;
    feat1_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    feat1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    feat1_we1 : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    input_ftmap_ap_vld : IN STD_LOGIC;
    conv1_weights_ap_vld : IN STD_LOGIC;
    conv1_biases_ap_vld : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of srcnn_conv1 is 
    constant ap_const_lv22_0 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal entry_proc_U0_ap_start : STD_LOGIC;
    signal entry_proc_U0_ap_done : STD_LOGIC;
    signal entry_proc_U0_ap_continue : STD_LOGIC;
    signal entry_proc_U0_ap_idle : STD_LOGIC;
    signal entry_proc_U0_ap_ready : STD_LOGIC;
    signal entry_proc_U0_start_out : STD_LOGIC;
    signal entry_proc_U0_start_write : STD_LOGIC;
    signal entry_proc_U0_input_ftmap_c_din : STD_LOGIC_VECTOR (63 downto 0);
    signal entry_proc_U0_input_ftmap_c_write : STD_LOGIC;
    signal entry_proc_U0_conv1_weights_c_din : STD_LOGIC_VECTOR (63 downto 0);
    signal entry_proc_U0_conv1_weights_c_write : STD_LOGIC;
    signal entry_proc_U0_conv1_biases_c_din : STD_LOGIC_VECTOR (63 downto 0);
    signal entry_proc_U0_conv1_biases_c_write : STD_LOGIC;
    signal gen_tiles_stream_all_U0_ap_start : STD_LOGIC;
    signal gen_tiles_stream_all_U0_ap_done : STD_LOGIC;
    signal gen_tiles_stream_all_U0_ap_continue : STD_LOGIC;
    signal gen_tiles_stream_all_U0_ap_idle : STD_LOGIC;
    signal gen_tiles_stream_all_U0_ap_ready : STD_LOGIC;
    signal gen_tiles_stream_all_U0_q0_din : STD_LOGIC_VECTOR (223 downto 0);
    signal gen_tiles_stream_all_U0_q0_write : STD_LOGIC;
    signal load_stage_U0_ap_start : STD_LOGIC;
    signal load_stage_U0_ap_done : STD_LOGIC;
    signal load_stage_U0_ap_continue : STD_LOGIC;
    signal load_stage_U0_ap_idle : STD_LOGIC;
    signal load_stage_U0_ap_ready : STD_LOGIC;
    signal load_stage_U0_start_out : STD_LOGIC;
    signal load_stage_U0_start_write : STD_LOGIC;
    signal load_stage_U0_q0_read : STD_LOGIC;
    signal load_stage_U0_m_axi_gmem_in_AWVALID : STD_LOGIC;
    signal load_stage_U0_m_axi_gmem_in_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal load_stage_U0_m_axi_gmem_in_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal load_stage_U0_m_axi_gmem_in_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal load_stage_U0_m_axi_gmem_in_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal load_stage_U0_m_axi_gmem_in_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal load_stage_U0_m_axi_gmem_in_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal load_stage_U0_m_axi_gmem_in_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal load_stage_U0_m_axi_gmem_in_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal load_stage_U0_m_axi_gmem_in_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal load_stage_U0_m_axi_gmem_in_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal load_stage_U0_m_axi_gmem_in_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal load_stage_U0_m_axi_gmem_in_WVALID : STD_LOGIC;
    signal load_stage_U0_m_axi_gmem_in_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal load_stage_U0_m_axi_gmem_in_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal load_stage_U0_m_axi_gmem_in_WLAST : STD_LOGIC;
    signal load_stage_U0_m_axi_gmem_in_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal load_stage_U0_m_axi_gmem_in_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal load_stage_U0_m_axi_gmem_in_ARVALID : STD_LOGIC;
    signal load_stage_U0_m_axi_gmem_in_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal load_stage_U0_m_axi_gmem_in_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal load_stage_U0_m_axi_gmem_in_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal load_stage_U0_m_axi_gmem_in_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal load_stage_U0_m_axi_gmem_in_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal load_stage_U0_m_axi_gmem_in_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal load_stage_U0_m_axi_gmem_in_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal load_stage_U0_m_axi_gmem_in_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal load_stage_U0_m_axi_gmem_in_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal load_stage_U0_m_axi_gmem_in_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal load_stage_U0_m_axi_gmem_in_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal load_stage_U0_m_axi_gmem_in_RREADY : STD_LOGIC;
    signal load_stage_U0_m_axi_gmem_in_BREADY : STD_LOGIC;
    signal load_stage_U0_input_ftmap_read : STD_LOGIC;
    signal load_stage_U0_m_axi_gmem_wgt_AWVALID : STD_LOGIC;
    signal load_stage_U0_m_axi_gmem_wgt_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal load_stage_U0_m_axi_gmem_wgt_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal load_stage_U0_m_axi_gmem_wgt_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal load_stage_U0_m_axi_gmem_wgt_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal load_stage_U0_m_axi_gmem_wgt_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal load_stage_U0_m_axi_gmem_wgt_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal load_stage_U0_m_axi_gmem_wgt_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal load_stage_U0_m_axi_gmem_wgt_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal load_stage_U0_m_axi_gmem_wgt_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal load_stage_U0_m_axi_gmem_wgt_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal load_stage_U0_m_axi_gmem_wgt_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal load_stage_U0_m_axi_gmem_wgt_WVALID : STD_LOGIC;
    signal load_stage_U0_m_axi_gmem_wgt_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal load_stage_U0_m_axi_gmem_wgt_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal load_stage_U0_m_axi_gmem_wgt_WLAST : STD_LOGIC;
    signal load_stage_U0_m_axi_gmem_wgt_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal load_stage_U0_m_axi_gmem_wgt_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal load_stage_U0_m_axi_gmem_wgt_ARVALID : STD_LOGIC;
    signal load_stage_U0_m_axi_gmem_wgt_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal load_stage_U0_m_axi_gmem_wgt_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal load_stage_U0_m_axi_gmem_wgt_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal load_stage_U0_m_axi_gmem_wgt_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal load_stage_U0_m_axi_gmem_wgt_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal load_stage_U0_m_axi_gmem_wgt_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal load_stage_U0_m_axi_gmem_wgt_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal load_stage_U0_m_axi_gmem_wgt_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal load_stage_U0_m_axi_gmem_wgt_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal load_stage_U0_m_axi_gmem_wgt_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal load_stage_U0_m_axi_gmem_wgt_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal load_stage_U0_m_axi_gmem_wgt_RREADY : STD_LOGIC;
    signal load_stage_U0_m_axi_gmem_wgt_BREADY : STD_LOGIC;
    signal load_stage_U0_conv1_weights_read : STD_LOGIC;
    signal load_stage_U0_conv1_biases_read : STD_LOGIC;
    signal load_stage_U0_q1_din : STD_LOGIC_VECTOR (223 downto 0);
    signal load_stage_U0_q1_write : STD_LOGIC;
    signal load_stage_U0_s_bias_din : STD_LOGIC_VECTOR (31 downto 0);
    signal load_stage_U0_s_bias_write : STD_LOGIC;
    signal load_stage_U0_s_in_din : STD_LOGIC_VECTOR (31 downto 0);
    signal load_stage_U0_s_in_write : STD_LOGIC;
    signal load_stage_U0_s_w_din : STD_LOGIC_VECTOR (31 downto 0);
    signal load_stage_U0_s_w_write : STD_LOGIC;
    signal compute_stage_U0_ap_start : STD_LOGIC;
    signal compute_stage_U0_ap_done : STD_LOGIC;
    signal compute_stage_U0_ap_continue : STD_LOGIC;
    signal compute_stage_U0_ap_idle : STD_LOGIC;
    signal compute_stage_U0_ap_ready : STD_LOGIC;
    signal compute_stage_U0_start_out : STD_LOGIC;
    signal compute_stage_U0_start_write : STD_LOGIC;
    signal compute_stage_U0_q1_read : STD_LOGIC;
    signal compute_stage_U0_s_bias_read : STD_LOGIC;
    signal compute_stage_U0_s_in_read : STD_LOGIC;
    signal compute_stage_U0_s_w_read : STD_LOGIC;
    signal compute_stage_U0_q2_din : STD_LOGIC_VECTOR (223 downto 0);
    signal compute_stage_U0_q2_write : STD_LOGIC;
    signal compute_stage_U0_s_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal compute_stage_U0_s_out_write : STD_LOGIC;
    signal store_stage_U0_ap_start : STD_LOGIC;
    signal store_stage_U0_ap_done : STD_LOGIC;
    signal store_stage_U0_ap_continue : STD_LOGIC;
    signal store_stage_U0_ap_idle : STD_LOGIC;
    signal store_stage_U0_ap_ready : STD_LOGIC;
    signal store_stage_U0_q2_read : STD_LOGIC;
    signal store_stage_U0_s_out_read : STD_LOGIC;
    signal store_stage_U0_feat1_address0 : STD_LOGIC_VECTOR (21 downto 0);
    signal store_stage_U0_feat1_ce0 : STD_LOGIC;
    signal store_stage_U0_feat1_we0 : STD_LOGIC;
    signal store_stage_U0_feat1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal input_ftmap_c_full_n : STD_LOGIC;
    signal input_ftmap_c_dout : STD_LOGIC_VECTOR (63 downto 0);
    signal input_ftmap_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal input_ftmap_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal input_ftmap_c_empty_n : STD_LOGIC;
    signal conv1_weights_c_full_n : STD_LOGIC;
    signal conv1_weights_c_dout : STD_LOGIC_VECTOR (63 downto 0);
    signal conv1_weights_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal conv1_weights_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal conv1_weights_c_empty_n : STD_LOGIC;
    signal conv1_biases_c_full_n : STD_LOGIC;
    signal conv1_biases_c_dout : STD_LOGIC_VECTOR (63 downto 0);
    signal conv1_biases_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal conv1_biases_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal conv1_biases_c_empty_n : STD_LOGIC;
    signal q0_full_n : STD_LOGIC;
    signal q0_dout : STD_LOGIC_VECTOR (223 downto 0);
    signal q0_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal q0_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal q0_empty_n : STD_LOGIC;
    signal q1_full_n : STD_LOGIC;
    signal q1_dout : STD_LOGIC_VECTOR (223 downto 0);
    signal q1_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal q1_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal q1_empty_n : STD_LOGIC;
    signal s_bias_full_n : STD_LOGIC;
    signal s_bias_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal s_bias_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal s_bias_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal s_bias_empty_n : STD_LOGIC;
    signal s_in_full_n : STD_LOGIC;
    signal s_in_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal s_in_num_data_valid : STD_LOGIC_VECTOR (6 downto 0);
    signal s_in_fifo_cap : STD_LOGIC_VECTOR (6 downto 0);
    signal s_in_empty_n : STD_LOGIC;
    signal s_w_full_n : STD_LOGIC;
    signal s_w_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal s_w_num_data_valid : STD_LOGIC_VECTOR (6 downto 0);
    signal s_w_fifo_cap : STD_LOGIC_VECTOR (6 downto 0);
    signal s_w_empty_n : STD_LOGIC;
    signal q2_full_n : STD_LOGIC;
    signal q2_dout : STD_LOGIC_VECTOR (223 downto 0);
    signal q2_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal q2_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal q2_empty_n : STD_LOGIC;
    signal s_out_full_n : STD_LOGIC;
    signal s_out_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal s_out_num_data_valid : STD_LOGIC_VECTOR (8 downto 0);
    signal s_out_fifo_cap : STD_LOGIC_VECTOR (8 downto 0);
    signal s_out_empty_n : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_entry_proc_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_entry_proc_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_gen_tiles_stream_all_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_gen_tiles_stream_all_U0_ap_ready : STD_LOGIC;
    signal start_for_load_stage_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_load_stage_U0_full_n : STD_LOGIC;
    signal start_for_load_stage_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_load_stage_U0_empty_n : STD_LOGIC;
    signal start_for_compute_stage_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_compute_stage_U0_full_n : STD_LOGIC;
    signal start_for_compute_stage_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_compute_stage_U0_empty_n : STD_LOGIC;
    signal start_for_store_stage_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_store_stage_U0_full_n : STD_LOGIC;
    signal start_for_store_stage_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_store_stage_U0_empty_n : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component srcnn_entry_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        input_ftmap : IN STD_LOGIC_VECTOR (63 downto 0);
        input_ftmap_c_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        input_ftmap_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        input_ftmap_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        input_ftmap_c_full_n : IN STD_LOGIC;
        input_ftmap_c_write : OUT STD_LOGIC;
        conv1_weights : IN STD_LOGIC_VECTOR (63 downto 0);
        conv1_weights_c_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        conv1_weights_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        conv1_weights_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        conv1_weights_c_full_n : IN STD_LOGIC;
        conv1_weights_c_write : OUT STD_LOGIC;
        conv1_biases : IN STD_LOGIC_VECTOR (63 downto 0);
        conv1_biases_c_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        conv1_biases_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        conv1_biases_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        conv1_biases_c_full_n : IN STD_LOGIC;
        conv1_biases_c_write : OUT STD_LOGIC );
    end component;


    component srcnn_gen_tiles_stream_all IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        q0_din : OUT STD_LOGIC_VECTOR (223 downto 0);
        q0_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        q0_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        q0_full_n : IN STD_LOGIC;
        q0_write : OUT STD_LOGIC );
    end component;


    component srcnn_load_stage IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        q0_dout : IN STD_LOGIC_VECTOR (223 downto 0);
        q0_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        q0_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        q0_empty_n : IN STD_LOGIC;
        q0_read : OUT STD_LOGIC;
        m_axi_gmem_in_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_in_AWREADY : IN STD_LOGIC;
        m_axi_gmem_in_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_in_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_in_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_in_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_in_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_in_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_in_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_in_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_in_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_in_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_in_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_in_WVALID : OUT STD_LOGIC;
        m_axi_gmem_in_WREADY : IN STD_LOGIC;
        m_axi_gmem_in_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_in_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_in_WLAST : OUT STD_LOGIC;
        m_axi_gmem_in_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_in_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_in_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_in_ARREADY : IN STD_LOGIC;
        m_axi_gmem_in_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_in_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_in_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_in_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_in_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_in_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_in_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_in_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_in_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_in_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_in_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_in_RVALID : IN STD_LOGIC;
        m_axi_gmem_in_RREADY : OUT STD_LOGIC;
        m_axi_gmem_in_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_in_RLAST : IN STD_LOGIC;
        m_axi_gmem_in_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_in_RFIFONUM : IN STD_LOGIC_VECTOR (12 downto 0);
        m_axi_gmem_in_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_in_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_in_BVALID : IN STD_LOGIC;
        m_axi_gmem_in_BREADY : OUT STD_LOGIC;
        m_axi_gmem_in_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_in_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_in_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        input_ftmap_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        input_ftmap_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        input_ftmap_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        input_ftmap_empty_n : IN STD_LOGIC;
        input_ftmap_read : OUT STD_LOGIC;
        m_axi_gmem_wgt_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_wgt_AWREADY : IN STD_LOGIC;
        m_axi_gmem_wgt_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_wgt_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_wgt_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_wgt_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_wgt_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_wgt_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_wgt_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_wgt_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_wgt_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_wgt_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_wgt_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_wgt_WVALID : OUT STD_LOGIC;
        m_axi_gmem_wgt_WREADY : IN STD_LOGIC;
        m_axi_gmem_wgt_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_wgt_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_wgt_WLAST : OUT STD_LOGIC;
        m_axi_gmem_wgt_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_wgt_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_wgt_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_wgt_ARREADY : IN STD_LOGIC;
        m_axi_gmem_wgt_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_wgt_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_wgt_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_wgt_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_wgt_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_wgt_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_wgt_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_wgt_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_wgt_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_wgt_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_wgt_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_wgt_RVALID : IN STD_LOGIC;
        m_axi_gmem_wgt_RREADY : OUT STD_LOGIC;
        m_axi_gmem_wgt_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_wgt_RLAST : IN STD_LOGIC;
        m_axi_gmem_wgt_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_wgt_RFIFONUM : IN STD_LOGIC_VECTOR (13 downto 0);
        m_axi_gmem_wgt_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_wgt_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_wgt_BVALID : IN STD_LOGIC;
        m_axi_gmem_wgt_BREADY : OUT STD_LOGIC;
        m_axi_gmem_wgt_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_wgt_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_wgt_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        conv1_weights_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        conv1_weights_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        conv1_weights_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        conv1_weights_empty_n : IN STD_LOGIC;
        conv1_weights_read : OUT STD_LOGIC;
        conv1_biases_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        conv1_biases_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        conv1_biases_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        conv1_biases_empty_n : IN STD_LOGIC;
        conv1_biases_read : OUT STD_LOGIC;
        q1_din : OUT STD_LOGIC_VECTOR (223 downto 0);
        q1_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        q1_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        q1_full_n : IN STD_LOGIC;
        q1_write : OUT STD_LOGIC;
        s_bias_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        s_bias_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        s_bias_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        s_bias_full_n : IN STD_LOGIC;
        s_bias_write : OUT STD_LOGIC;
        s_in_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        s_in_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        s_in_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        s_in_full_n : IN STD_LOGIC;
        s_in_write : OUT STD_LOGIC;
        s_w_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        s_w_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        s_w_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        s_w_full_n : IN STD_LOGIC;
        s_w_write : OUT STD_LOGIC );
    end component;


    component srcnn_compute_stage IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        q1_dout : IN STD_LOGIC_VECTOR (223 downto 0);
        q1_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        q1_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        q1_empty_n : IN STD_LOGIC;
        q1_read : OUT STD_LOGIC;
        s_bias_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        s_bias_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        s_bias_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        s_bias_empty_n : IN STD_LOGIC;
        s_bias_read : OUT STD_LOGIC;
        s_in_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        s_in_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        s_in_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        s_in_empty_n : IN STD_LOGIC;
        s_in_read : OUT STD_LOGIC;
        s_w_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        s_w_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        s_w_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        s_w_empty_n : IN STD_LOGIC;
        s_w_read : OUT STD_LOGIC;
        q2_din : OUT STD_LOGIC_VECTOR (223 downto 0);
        q2_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        q2_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        q2_full_n : IN STD_LOGIC;
        q2_write : OUT STD_LOGIC;
        s_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        s_out_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        s_out_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
        s_out_full_n : IN STD_LOGIC;
        s_out_write : OUT STD_LOGIC );
    end component;


    component srcnn_store_stage IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        q2_dout : IN STD_LOGIC_VECTOR (223 downto 0);
        q2_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        q2_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        q2_empty_n : IN STD_LOGIC;
        q2_read : OUT STD_LOGIC;
        s_out_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        s_out_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        s_out_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
        s_out_empty_n : IN STD_LOGIC;
        s_out_read : OUT STD_LOGIC;
        feat1_address0 : OUT STD_LOGIC_VECTOR (21 downto 0);
        feat1_ce0 : OUT STD_LOGIC;
        feat1_we0 : OUT STD_LOGIC;
        feat1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component srcnn_fifo_w64_d3_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (63 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (63 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component srcnn_fifo_w224_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (223 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (223 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component srcnn_fifo_w32_d4_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component srcnn_fifo_w32_d64_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (6 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (6 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component srcnn_fifo_w32_d256_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (8 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (8 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component srcnn_start_for_load_stage_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component srcnn_start_for_compute_stage_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component srcnn_start_for_store_stage_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    entry_proc_U0 : component srcnn_entry_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => entry_proc_U0_ap_start,
        start_full_n => start_for_load_stage_U0_full_n,
        ap_done => entry_proc_U0_ap_done,
        ap_continue => entry_proc_U0_ap_continue,
        ap_idle => entry_proc_U0_ap_idle,
        ap_ready => entry_proc_U0_ap_ready,
        start_out => entry_proc_U0_start_out,
        start_write => entry_proc_U0_start_write,
        input_ftmap => input_ftmap,
        input_ftmap_c_din => entry_proc_U0_input_ftmap_c_din,
        input_ftmap_c_num_data_valid => input_ftmap_c_num_data_valid,
        input_ftmap_c_fifo_cap => input_ftmap_c_fifo_cap,
        input_ftmap_c_full_n => input_ftmap_c_full_n,
        input_ftmap_c_write => entry_proc_U0_input_ftmap_c_write,
        conv1_weights => conv1_weights,
        conv1_weights_c_din => entry_proc_U0_conv1_weights_c_din,
        conv1_weights_c_num_data_valid => conv1_weights_c_num_data_valid,
        conv1_weights_c_fifo_cap => conv1_weights_c_fifo_cap,
        conv1_weights_c_full_n => conv1_weights_c_full_n,
        conv1_weights_c_write => entry_proc_U0_conv1_weights_c_write,
        conv1_biases => conv1_biases,
        conv1_biases_c_din => entry_proc_U0_conv1_biases_c_din,
        conv1_biases_c_num_data_valid => conv1_biases_c_num_data_valid,
        conv1_biases_c_fifo_cap => conv1_biases_c_fifo_cap,
        conv1_biases_c_full_n => conv1_biases_c_full_n,
        conv1_biases_c_write => entry_proc_U0_conv1_biases_c_write);

    gen_tiles_stream_all_U0 : component srcnn_gen_tiles_stream_all
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => gen_tiles_stream_all_U0_ap_start,
        ap_done => gen_tiles_stream_all_U0_ap_done,
        ap_continue => gen_tiles_stream_all_U0_ap_continue,
        ap_idle => gen_tiles_stream_all_U0_ap_idle,
        ap_ready => gen_tiles_stream_all_U0_ap_ready,
        q0_din => gen_tiles_stream_all_U0_q0_din,
        q0_num_data_valid => q0_num_data_valid,
        q0_fifo_cap => q0_fifo_cap,
        q0_full_n => q0_full_n,
        q0_write => gen_tiles_stream_all_U0_q0_write);

    load_stage_U0 : component srcnn_load_stage
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => load_stage_U0_ap_start,
        start_full_n => start_for_compute_stage_U0_full_n,
        ap_done => load_stage_U0_ap_done,
        ap_continue => load_stage_U0_ap_continue,
        ap_idle => load_stage_U0_ap_idle,
        ap_ready => load_stage_U0_ap_ready,
        start_out => load_stage_U0_start_out,
        start_write => load_stage_U0_start_write,
        q0_dout => q0_dout,
        q0_num_data_valid => q0_num_data_valid,
        q0_fifo_cap => q0_fifo_cap,
        q0_empty_n => q0_empty_n,
        q0_read => load_stage_U0_q0_read,
        m_axi_gmem_in_AWVALID => load_stage_U0_m_axi_gmem_in_AWVALID,
        m_axi_gmem_in_AWREADY => ap_const_logic_0,
        m_axi_gmem_in_AWADDR => load_stage_U0_m_axi_gmem_in_AWADDR,
        m_axi_gmem_in_AWID => load_stage_U0_m_axi_gmem_in_AWID,
        m_axi_gmem_in_AWLEN => load_stage_U0_m_axi_gmem_in_AWLEN,
        m_axi_gmem_in_AWSIZE => load_stage_U0_m_axi_gmem_in_AWSIZE,
        m_axi_gmem_in_AWBURST => load_stage_U0_m_axi_gmem_in_AWBURST,
        m_axi_gmem_in_AWLOCK => load_stage_U0_m_axi_gmem_in_AWLOCK,
        m_axi_gmem_in_AWCACHE => load_stage_U0_m_axi_gmem_in_AWCACHE,
        m_axi_gmem_in_AWPROT => load_stage_U0_m_axi_gmem_in_AWPROT,
        m_axi_gmem_in_AWQOS => load_stage_U0_m_axi_gmem_in_AWQOS,
        m_axi_gmem_in_AWREGION => load_stage_U0_m_axi_gmem_in_AWREGION,
        m_axi_gmem_in_AWUSER => load_stage_U0_m_axi_gmem_in_AWUSER,
        m_axi_gmem_in_WVALID => load_stage_U0_m_axi_gmem_in_WVALID,
        m_axi_gmem_in_WREADY => ap_const_logic_0,
        m_axi_gmem_in_WDATA => load_stage_U0_m_axi_gmem_in_WDATA,
        m_axi_gmem_in_WSTRB => load_stage_U0_m_axi_gmem_in_WSTRB,
        m_axi_gmem_in_WLAST => load_stage_U0_m_axi_gmem_in_WLAST,
        m_axi_gmem_in_WID => load_stage_U0_m_axi_gmem_in_WID,
        m_axi_gmem_in_WUSER => load_stage_U0_m_axi_gmem_in_WUSER,
        m_axi_gmem_in_ARVALID => load_stage_U0_m_axi_gmem_in_ARVALID,
        m_axi_gmem_in_ARREADY => m_axi_gmem_in_ARREADY,
        m_axi_gmem_in_ARADDR => load_stage_U0_m_axi_gmem_in_ARADDR,
        m_axi_gmem_in_ARID => load_stage_U0_m_axi_gmem_in_ARID,
        m_axi_gmem_in_ARLEN => load_stage_U0_m_axi_gmem_in_ARLEN,
        m_axi_gmem_in_ARSIZE => load_stage_U0_m_axi_gmem_in_ARSIZE,
        m_axi_gmem_in_ARBURST => load_stage_U0_m_axi_gmem_in_ARBURST,
        m_axi_gmem_in_ARLOCK => load_stage_U0_m_axi_gmem_in_ARLOCK,
        m_axi_gmem_in_ARCACHE => load_stage_U0_m_axi_gmem_in_ARCACHE,
        m_axi_gmem_in_ARPROT => load_stage_U0_m_axi_gmem_in_ARPROT,
        m_axi_gmem_in_ARQOS => load_stage_U0_m_axi_gmem_in_ARQOS,
        m_axi_gmem_in_ARREGION => load_stage_U0_m_axi_gmem_in_ARREGION,
        m_axi_gmem_in_ARUSER => load_stage_U0_m_axi_gmem_in_ARUSER,
        m_axi_gmem_in_RVALID => m_axi_gmem_in_RVALID,
        m_axi_gmem_in_RREADY => load_stage_U0_m_axi_gmem_in_RREADY,
        m_axi_gmem_in_RDATA => m_axi_gmem_in_RDATA,
        m_axi_gmem_in_RLAST => m_axi_gmem_in_RLAST,
        m_axi_gmem_in_RID => m_axi_gmem_in_RID,
        m_axi_gmem_in_RFIFONUM => m_axi_gmem_in_RFIFONUM,
        m_axi_gmem_in_RUSER => m_axi_gmem_in_RUSER,
        m_axi_gmem_in_RRESP => m_axi_gmem_in_RRESP,
        m_axi_gmem_in_BVALID => ap_const_logic_0,
        m_axi_gmem_in_BREADY => load_stage_U0_m_axi_gmem_in_BREADY,
        m_axi_gmem_in_BRESP => ap_const_lv2_0,
        m_axi_gmem_in_BID => ap_const_lv1_0,
        m_axi_gmem_in_BUSER => ap_const_lv1_0,
        input_ftmap_dout => input_ftmap_c_dout,
        input_ftmap_num_data_valid => input_ftmap_c_num_data_valid,
        input_ftmap_fifo_cap => input_ftmap_c_fifo_cap,
        input_ftmap_empty_n => input_ftmap_c_empty_n,
        input_ftmap_read => load_stage_U0_input_ftmap_read,
        m_axi_gmem_wgt_AWVALID => load_stage_U0_m_axi_gmem_wgt_AWVALID,
        m_axi_gmem_wgt_AWREADY => ap_const_logic_0,
        m_axi_gmem_wgt_AWADDR => load_stage_U0_m_axi_gmem_wgt_AWADDR,
        m_axi_gmem_wgt_AWID => load_stage_U0_m_axi_gmem_wgt_AWID,
        m_axi_gmem_wgt_AWLEN => load_stage_U0_m_axi_gmem_wgt_AWLEN,
        m_axi_gmem_wgt_AWSIZE => load_stage_U0_m_axi_gmem_wgt_AWSIZE,
        m_axi_gmem_wgt_AWBURST => load_stage_U0_m_axi_gmem_wgt_AWBURST,
        m_axi_gmem_wgt_AWLOCK => load_stage_U0_m_axi_gmem_wgt_AWLOCK,
        m_axi_gmem_wgt_AWCACHE => load_stage_U0_m_axi_gmem_wgt_AWCACHE,
        m_axi_gmem_wgt_AWPROT => load_stage_U0_m_axi_gmem_wgt_AWPROT,
        m_axi_gmem_wgt_AWQOS => load_stage_U0_m_axi_gmem_wgt_AWQOS,
        m_axi_gmem_wgt_AWREGION => load_stage_U0_m_axi_gmem_wgt_AWREGION,
        m_axi_gmem_wgt_AWUSER => load_stage_U0_m_axi_gmem_wgt_AWUSER,
        m_axi_gmem_wgt_WVALID => load_stage_U0_m_axi_gmem_wgt_WVALID,
        m_axi_gmem_wgt_WREADY => ap_const_logic_0,
        m_axi_gmem_wgt_WDATA => load_stage_U0_m_axi_gmem_wgt_WDATA,
        m_axi_gmem_wgt_WSTRB => load_stage_U0_m_axi_gmem_wgt_WSTRB,
        m_axi_gmem_wgt_WLAST => load_stage_U0_m_axi_gmem_wgt_WLAST,
        m_axi_gmem_wgt_WID => load_stage_U0_m_axi_gmem_wgt_WID,
        m_axi_gmem_wgt_WUSER => load_stage_U0_m_axi_gmem_wgt_WUSER,
        m_axi_gmem_wgt_ARVALID => load_stage_U0_m_axi_gmem_wgt_ARVALID,
        m_axi_gmem_wgt_ARREADY => m_axi_gmem_wgt_ARREADY,
        m_axi_gmem_wgt_ARADDR => load_stage_U0_m_axi_gmem_wgt_ARADDR,
        m_axi_gmem_wgt_ARID => load_stage_U0_m_axi_gmem_wgt_ARID,
        m_axi_gmem_wgt_ARLEN => load_stage_U0_m_axi_gmem_wgt_ARLEN,
        m_axi_gmem_wgt_ARSIZE => load_stage_U0_m_axi_gmem_wgt_ARSIZE,
        m_axi_gmem_wgt_ARBURST => load_stage_U0_m_axi_gmem_wgt_ARBURST,
        m_axi_gmem_wgt_ARLOCK => load_stage_U0_m_axi_gmem_wgt_ARLOCK,
        m_axi_gmem_wgt_ARCACHE => load_stage_U0_m_axi_gmem_wgt_ARCACHE,
        m_axi_gmem_wgt_ARPROT => load_stage_U0_m_axi_gmem_wgt_ARPROT,
        m_axi_gmem_wgt_ARQOS => load_stage_U0_m_axi_gmem_wgt_ARQOS,
        m_axi_gmem_wgt_ARREGION => load_stage_U0_m_axi_gmem_wgt_ARREGION,
        m_axi_gmem_wgt_ARUSER => load_stage_U0_m_axi_gmem_wgt_ARUSER,
        m_axi_gmem_wgt_RVALID => m_axi_gmem_wgt_RVALID,
        m_axi_gmem_wgt_RREADY => load_stage_U0_m_axi_gmem_wgt_RREADY,
        m_axi_gmem_wgt_RDATA => m_axi_gmem_wgt_RDATA,
        m_axi_gmem_wgt_RLAST => m_axi_gmem_wgt_RLAST,
        m_axi_gmem_wgt_RID => m_axi_gmem_wgt_RID,
        m_axi_gmem_wgt_RFIFONUM => m_axi_gmem_wgt_RFIFONUM,
        m_axi_gmem_wgt_RUSER => m_axi_gmem_wgt_RUSER,
        m_axi_gmem_wgt_RRESP => m_axi_gmem_wgt_RRESP,
        m_axi_gmem_wgt_BVALID => ap_const_logic_0,
        m_axi_gmem_wgt_BREADY => load_stage_U0_m_axi_gmem_wgt_BREADY,
        m_axi_gmem_wgt_BRESP => ap_const_lv2_0,
        m_axi_gmem_wgt_BID => ap_const_lv1_0,
        m_axi_gmem_wgt_BUSER => ap_const_lv1_0,
        conv1_weights_dout => conv1_weights_c_dout,
        conv1_weights_num_data_valid => conv1_weights_c_num_data_valid,
        conv1_weights_fifo_cap => conv1_weights_c_fifo_cap,
        conv1_weights_empty_n => conv1_weights_c_empty_n,
        conv1_weights_read => load_stage_U0_conv1_weights_read,
        conv1_biases_dout => conv1_biases_c_dout,
        conv1_biases_num_data_valid => conv1_biases_c_num_data_valid,
        conv1_biases_fifo_cap => conv1_biases_c_fifo_cap,
        conv1_biases_empty_n => conv1_biases_c_empty_n,
        conv1_biases_read => load_stage_U0_conv1_biases_read,
        q1_din => load_stage_U0_q1_din,
        q1_num_data_valid => q1_num_data_valid,
        q1_fifo_cap => q1_fifo_cap,
        q1_full_n => q1_full_n,
        q1_write => load_stage_U0_q1_write,
        s_bias_din => load_stage_U0_s_bias_din,
        s_bias_num_data_valid => s_bias_num_data_valid,
        s_bias_fifo_cap => s_bias_fifo_cap,
        s_bias_full_n => s_bias_full_n,
        s_bias_write => load_stage_U0_s_bias_write,
        s_in_din => load_stage_U0_s_in_din,
        s_in_num_data_valid => s_in_num_data_valid,
        s_in_fifo_cap => s_in_fifo_cap,
        s_in_full_n => s_in_full_n,
        s_in_write => load_stage_U0_s_in_write,
        s_w_din => load_stage_U0_s_w_din,
        s_w_num_data_valid => s_w_num_data_valid,
        s_w_fifo_cap => s_w_fifo_cap,
        s_w_full_n => s_w_full_n,
        s_w_write => load_stage_U0_s_w_write);

    compute_stage_U0 : component srcnn_compute_stage
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => compute_stage_U0_ap_start,
        start_full_n => start_for_store_stage_U0_full_n,
        ap_done => compute_stage_U0_ap_done,
        ap_continue => compute_stage_U0_ap_continue,
        ap_idle => compute_stage_U0_ap_idle,
        ap_ready => compute_stage_U0_ap_ready,
        start_out => compute_stage_U0_start_out,
        start_write => compute_stage_U0_start_write,
        q1_dout => q1_dout,
        q1_num_data_valid => q1_num_data_valid,
        q1_fifo_cap => q1_fifo_cap,
        q1_empty_n => q1_empty_n,
        q1_read => compute_stage_U0_q1_read,
        s_bias_dout => s_bias_dout,
        s_bias_num_data_valid => s_bias_num_data_valid,
        s_bias_fifo_cap => s_bias_fifo_cap,
        s_bias_empty_n => s_bias_empty_n,
        s_bias_read => compute_stage_U0_s_bias_read,
        s_in_dout => s_in_dout,
        s_in_num_data_valid => s_in_num_data_valid,
        s_in_fifo_cap => s_in_fifo_cap,
        s_in_empty_n => s_in_empty_n,
        s_in_read => compute_stage_U0_s_in_read,
        s_w_dout => s_w_dout,
        s_w_num_data_valid => s_w_num_data_valid,
        s_w_fifo_cap => s_w_fifo_cap,
        s_w_empty_n => s_w_empty_n,
        s_w_read => compute_stage_U0_s_w_read,
        q2_din => compute_stage_U0_q2_din,
        q2_num_data_valid => q2_num_data_valid,
        q2_fifo_cap => q2_fifo_cap,
        q2_full_n => q2_full_n,
        q2_write => compute_stage_U0_q2_write,
        s_out_din => compute_stage_U0_s_out_din,
        s_out_num_data_valid => s_out_num_data_valid,
        s_out_fifo_cap => s_out_fifo_cap,
        s_out_full_n => s_out_full_n,
        s_out_write => compute_stage_U0_s_out_write);

    store_stage_U0 : component srcnn_store_stage
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => store_stage_U0_ap_start,
        ap_done => store_stage_U0_ap_done,
        ap_continue => store_stage_U0_ap_continue,
        ap_idle => store_stage_U0_ap_idle,
        ap_ready => store_stage_U0_ap_ready,
        q2_dout => q2_dout,
        q2_num_data_valid => q2_num_data_valid,
        q2_fifo_cap => q2_fifo_cap,
        q2_empty_n => q2_empty_n,
        q2_read => store_stage_U0_q2_read,
        s_out_dout => s_out_dout,
        s_out_num_data_valid => s_out_num_data_valid,
        s_out_fifo_cap => s_out_fifo_cap,
        s_out_empty_n => s_out_empty_n,
        s_out_read => store_stage_U0_s_out_read,
        feat1_address0 => store_stage_U0_feat1_address0,
        feat1_ce0 => store_stage_U0_feat1_ce0,
        feat1_we0 => store_stage_U0_feat1_we0,
        feat1_d0 => store_stage_U0_feat1_d0);

    input_ftmap_c_U : component srcnn_fifo_w64_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_input_ftmap_c_din,
        if_full_n => input_ftmap_c_full_n,
        if_write => entry_proc_U0_input_ftmap_c_write,
        if_dout => input_ftmap_c_dout,
        if_num_data_valid => input_ftmap_c_num_data_valid,
        if_fifo_cap => input_ftmap_c_fifo_cap,
        if_empty_n => input_ftmap_c_empty_n,
        if_read => load_stage_U0_input_ftmap_read);

    conv1_weights_c_U : component srcnn_fifo_w64_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_conv1_weights_c_din,
        if_full_n => conv1_weights_c_full_n,
        if_write => entry_proc_U0_conv1_weights_c_write,
        if_dout => conv1_weights_c_dout,
        if_num_data_valid => conv1_weights_c_num_data_valid,
        if_fifo_cap => conv1_weights_c_fifo_cap,
        if_empty_n => conv1_weights_c_empty_n,
        if_read => load_stage_U0_conv1_weights_read);

    conv1_biases_c_U : component srcnn_fifo_w64_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_conv1_biases_c_din,
        if_full_n => conv1_biases_c_full_n,
        if_write => entry_proc_U0_conv1_biases_c_write,
        if_dout => conv1_biases_c_dout,
        if_num_data_valid => conv1_biases_c_num_data_valid,
        if_fifo_cap => conv1_biases_c_fifo_cap,
        if_empty_n => conv1_biases_c_empty_n,
        if_read => load_stage_U0_conv1_biases_read);

    q0_U : component srcnn_fifo_w224_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => gen_tiles_stream_all_U0_q0_din,
        if_full_n => q0_full_n,
        if_write => gen_tiles_stream_all_U0_q0_write,
        if_dout => q0_dout,
        if_num_data_valid => q0_num_data_valid,
        if_fifo_cap => q0_fifo_cap,
        if_empty_n => q0_empty_n,
        if_read => load_stage_U0_q0_read);

    q1_U : component srcnn_fifo_w224_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => load_stage_U0_q1_din,
        if_full_n => q1_full_n,
        if_write => load_stage_U0_q1_write,
        if_dout => q1_dout,
        if_num_data_valid => q1_num_data_valid,
        if_fifo_cap => q1_fifo_cap,
        if_empty_n => q1_empty_n,
        if_read => compute_stage_U0_q1_read);

    s_bias_U : component srcnn_fifo_w32_d4_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => load_stage_U0_s_bias_din,
        if_full_n => s_bias_full_n,
        if_write => load_stage_U0_s_bias_write,
        if_dout => s_bias_dout,
        if_num_data_valid => s_bias_num_data_valid,
        if_fifo_cap => s_bias_fifo_cap,
        if_empty_n => s_bias_empty_n,
        if_read => compute_stage_U0_s_bias_read);

    s_in_U : component srcnn_fifo_w32_d64_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => load_stage_U0_s_in_din,
        if_full_n => s_in_full_n,
        if_write => load_stage_U0_s_in_write,
        if_dout => s_in_dout,
        if_num_data_valid => s_in_num_data_valid,
        if_fifo_cap => s_in_fifo_cap,
        if_empty_n => s_in_empty_n,
        if_read => compute_stage_U0_s_in_read);

    s_w_U : component srcnn_fifo_w32_d64_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => load_stage_U0_s_w_din,
        if_full_n => s_w_full_n,
        if_write => load_stage_U0_s_w_write,
        if_dout => s_w_dout,
        if_num_data_valid => s_w_num_data_valid,
        if_fifo_cap => s_w_fifo_cap,
        if_empty_n => s_w_empty_n,
        if_read => compute_stage_U0_s_w_read);

    q2_U : component srcnn_fifo_w224_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => compute_stage_U0_q2_din,
        if_full_n => q2_full_n,
        if_write => compute_stage_U0_q2_write,
        if_dout => q2_dout,
        if_num_data_valid => q2_num_data_valid,
        if_fifo_cap => q2_fifo_cap,
        if_empty_n => q2_empty_n,
        if_read => store_stage_U0_q2_read);

    s_out_U : component srcnn_fifo_w32_d256_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => compute_stage_U0_s_out_din,
        if_full_n => s_out_full_n,
        if_write => compute_stage_U0_s_out_write,
        if_dout => s_out_dout,
        if_num_data_valid => s_out_num_data_valid,
        if_fifo_cap => s_out_fifo_cap,
        if_empty_n => s_out_empty_n,
        if_read => store_stage_U0_s_out_read);

    start_for_load_stage_U0_U : component srcnn_start_for_load_stage_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_load_stage_U0_din,
        if_full_n => start_for_load_stage_U0_full_n,
        if_write => entry_proc_U0_start_write,
        if_dout => start_for_load_stage_U0_dout,
        if_empty_n => start_for_load_stage_U0_empty_n,
        if_read => load_stage_U0_ap_ready);

    start_for_compute_stage_U0_U : component srcnn_start_for_compute_stage_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_compute_stage_U0_din,
        if_full_n => start_for_compute_stage_U0_full_n,
        if_write => load_stage_U0_start_write,
        if_dout => start_for_compute_stage_U0_dout,
        if_empty_n => start_for_compute_stage_U0_empty_n,
        if_read => compute_stage_U0_ap_ready);

    start_for_store_stage_U0_U : component srcnn_start_for_store_stage_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_store_stage_U0_din,
        if_full_n => start_for_store_stage_U0_full_n,
        if_write => compute_stage_U0_start_write,
        if_dout => start_for_store_stage_U0_dout,
        if_empty_n => start_for_store_stage_U0_empty_n,
        if_read => store_stage_U0_ap_ready);





    ap_sync_reg_entry_proc_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_entry_proc_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_entry_proc_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_gen_tiles_stream_all_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_gen_tiles_stream_all_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_gen_tiles_stream_all_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_gen_tiles_stream_all_U0_ap_ready <= ap_sync_gen_tiles_stream_all_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;

    ap_done <= store_stage_U0_ap_done;
    ap_idle <= (store_stage_U0_ap_idle and load_stage_U0_ap_idle and gen_tiles_stream_all_U0_ap_idle and entry_proc_U0_ap_idle and compute_stage_U0_ap_idle);
    ap_ready <= ap_sync_ready;
    ap_sync_entry_proc_U0_ap_ready <= (entry_proc_U0_ap_ready or ap_sync_reg_entry_proc_U0_ap_ready);
    ap_sync_gen_tiles_stream_all_U0_ap_ready <= (gen_tiles_stream_all_U0_ap_ready or ap_sync_reg_gen_tiles_stream_all_U0_ap_ready);
    ap_sync_ready <= (ap_sync_gen_tiles_stream_all_U0_ap_ready and ap_sync_entry_proc_U0_ap_ready);
    compute_stage_U0_ap_continue <= ap_const_logic_1;
    compute_stage_U0_ap_start <= start_for_compute_stage_U0_empty_n;
    entry_proc_U0_ap_continue <= ap_const_logic_1;
    entry_proc_U0_ap_start <= ((ap_sync_reg_entry_proc_U0_ap_ready xor ap_const_logic_1) and ap_start);
    feat1_address0 <= store_stage_U0_feat1_address0;
    feat1_address1 <= ap_const_lv22_0;
    feat1_ce0 <= store_stage_U0_feat1_ce0;
    feat1_ce1 <= ap_const_logic_0;
    feat1_d0 <= store_stage_U0_feat1_d0;
    feat1_d1 <= ap_const_lv32_0;
    feat1_we0 <= store_stage_U0_feat1_we0;
    feat1_we1 <= ap_const_logic_0;
    gen_tiles_stream_all_U0_ap_continue <= ap_const_logic_1;
    gen_tiles_stream_all_U0_ap_start <= ((ap_sync_reg_gen_tiles_stream_all_U0_ap_ready xor ap_const_logic_1) and ap_start);
    load_stage_U0_ap_continue <= ap_const_logic_1;
    load_stage_U0_ap_start <= start_for_load_stage_U0_empty_n;
    m_axi_gmem_in_ARADDR <= load_stage_U0_m_axi_gmem_in_ARADDR;
    m_axi_gmem_in_ARBURST <= load_stage_U0_m_axi_gmem_in_ARBURST;
    m_axi_gmem_in_ARCACHE <= load_stage_U0_m_axi_gmem_in_ARCACHE;
    m_axi_gmem_in_ARID <= load_stage_U0_m_axi_gmem_in_ARID;
    m_axi_gmem_in_ARLEN <= load_stage_U0_m_axi_gmem_in_ARLEN;
    m_axi_gmem_in_ARLOCK <= load_stage_U0_m_axi_gmem_in_ARLOCK;
    m_axi_gmem_in_ARPROT <= load_stage_U0_m_axi_gmem_in_ARPROT;
    m_axi_gmem_in_ARQOS <= load_stage_U0_m_axi_gmem_in_ARQOS;
    m_axi_gmem_in_ARREGION <= load_stage_U0_m_axi_gmem_in_ARREGION;
    m_axi_gmem_in_ARSIZE <= load_stage_U0_m_axi_gmem_in_ARSIZE;
    m_axi_gmem_in_ARUSER <= load_stage_U0_m_axi_gmem_in_ARUSER;
    m_axi_gmem_in_ARVALID <= load_stage_U0_m_axi_gmem_in_ARVALID;
    m_axi_gmem_in_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_in_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_in_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_in_AWID <= ap_const_lv1_0;
    m_axi_gmem_in_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_in_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_in_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_in_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_in_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_in_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_in_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_in_AWVALID <= ap_const_logic_0;
    m_axi_gmem_in_BREADY <= ap_const_logic_0;
    m_axi_gmem_in_RREADY <= load_stage_U0_m_axi_gmem_in_RREADY;
    m_axi_gmem_in_WDATA <= ap_const_lv32_0;
    m_axi_gmem_in_WID <= ap_const_lv1_0;
    m_axi_gmem_in_WLAST <= ap_const_logic_0;
    m_axi_gmem_in_WSTRB <= ap_const_lv4_0;
    m_axi_gmem_in_WUSER <= ap_const_lv1_0;
    m_axi_gmem_in_WVALID <= ap_const_logic_0;
    m_axi_gmem_wgt_ARADDR <= load_stage_U0_m_axi_gmem_wgt_ARADDR;
    m_axi_gmem_wgt_ARBURST <= load_stage_U0_m_axi_gmem_wgt_ARBURST;
    m_axi_gmem_wgt_ARCACHE <= load_stage_U0_m_axi_gmem_wgt_ARCACHE;
    m_axi_gmem_wgt_ARID <= load_stage_U0_m_axi_gmem_wgt_ARID;
    m_axi_gmem_wgt_ARLEN <= load_stage_U0_m_axi_gmem_wgt_ARLEN;
    m_axi_gmem_wgt_ARLOCK <= load_stage_U0_m_axi_gmem_wgt_ARLOCK;
    m_axi_gmem_wgt_ARPROT <= load_stage_U0_m_axi_gmem_wgt_ARPROT;
    m_axi_gmem_wgt_ARQOS <= load_stage_U0_m_axi_gmem_wgt_ARQOS;
    m_axi_gmem_wgt_ARREGION <= load_stage_U0_m_axi_gmem_wgt_ARREGION;
    m_axi_gmem_wgt_ARSIZE <= load_stage_U0_m_axi_gmem_wgt_ARSIZE;
    m_axi_gmem_wgt_ARUSER <= load_stage_U0_m_axi_gmem_wgt_ARUSER;
    m_axi_gmem_wgt_ARVALID <= load_stage_U0_m_axi_gmem_wgt_ARVALID;
    m_axi_gmem_wgt_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_wgt_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_wgt_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_wgt_AWID <= ap_const_lv1_0;
    m_axi_gmem_wgt_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_wgt_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_wgt_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_wgt_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_wgt_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_wgt_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_wgt_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_wgt_AWVALID <= ap_const_logic_0;
    m_axi_gmem_wgt_BREADY <= ap_const_logic_0;
    m_axi_gmem_wgt_RREADY <= load_stage_U0_m_axi_gmem_wgt_RREADY;
    m_axi_gmem_wgt_WDATA <= ap_const_lv32_0;
    m_axi_gmem_wgt_WID <= ap_const_lv1_0;
    m_axi_gmem_wgt_WLAST <= ap_const_logic_0;
    m_axi_gmem_wgt_WSTRB <= ap_const_lv4_0;
    m_axi_gmem_wgt_WUSER <= ap_const_lv1_0;
    m_axi_gmem_wgt_WVALID <= ap_const_logic_0;
    start_for_compute_stage_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_load_stage_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_store_stage_U0_din <= (0=>ap_const_logic_1, others=>'-');
    store_stage_U0_ap_continue <= ap_continue;
    store_stage_U0_ap_start <= start_for_store_stage_U0_empty_n;
end behav;
